// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CritereController from "./critere_controller"
application.register("critere", CritereController)

import EstimationController from "./estimation_controller"
application.register("estimation", EstimationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
